# docker-compose run --rm maven
# docker-compose run -it --rm maven:3.3-jdk-8 mvn clean

version: '3'
services:
  maven:
    build: .
    image: maven
    container_name: maven
    stdin_open: true 
    tty: true
    command: bash
    working_dir: /usr/src/mymaven
    volumes:
    - ./:/usr/src/mymaven
  